version: '3.9'

services:
  generic_app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: pythonformaids_app
    command: uvicorn api:app --host 0.0.0.0 --port 7700 --reload
    ports:
      - "7700"
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-cluster

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: pythonformaids_nginx
    volumes:
      - ./app/static:/static
      - ./nginx/config/:/etc/nginx/conf.d/
    networks:
      - app-cluster
    ports:
      - "80:80"
    depends_on:
      - generic_app

networks:
  app-cluster:
    name: internal_cluster
